apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
__RESOURCES__
namespace: sonataflow-infra

configurations:
- config/image-configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - secret.properties
    name: flightpathtestrepo-secret
configMapGenerator:
  - envs:
      - config.properties
    name: flightpathtestrepo-gitops

# Replace dev profile in SonataFlow instance(s), add image and envFrom
patches:
- path: sonataflow-patch.yaml
  target:
    kind: SonataFlow
    name: flightpathtestrepo
images:
- name: serverless-workflow-flightpathtestrepo
  newName: quay.io/rhdh-orchestrator-test/orchestrator-qe-ci
  newTag: __IMAGE_TAG__
